In [1]:
import pandas as pd
import numpy as np
import os
import re
import json as js
from pathlib import Path
from tqdm import tqdm
from ast import literal_eval

In [2]:
POS = ["v","a","n","pron","adv","num","p", "vt", "vi"]

def check_pos(data):
    cnt = 0
    
    for i in range(len(data)):
        dt = data[i]
        
        if dt[0] in POS:
            if i != 0:
                cnt += 1
            
    if cnt == 0:
        return False
    elif cnt > 1:
        return False
    else:
        return True


def categorize_anomali_entry(entry_font_size_pos, is_prakategorial):
    output = []
    
    for i in range(len(is_prakategorial)):
        padanan_lema = is_prakategorial[i]
        
        if padanan_lema == 1:
            
            if i == len(is_prakategorial)-1 :
                output.append(1)
            
            elif is_prakategorial[i+1] == 1:
                output.append(1)
            
            elif is_prakategorial[i+1] == 0 and not check_pos(entry_font_size_pos[i+1]):
                output.append(1)
            
            else:
                output.append(0)
                
        else:
            if not check_pos(entry_font_size_pos[i]):
                output.append(1)
            else:
                output.append(0)
    
    return output

In [ ]:
directory_CSV = "../../Ekstraksi/3. Preprocessing - Replace Kata Singkatan"
directory_hasil = "../../Ekstraksi/4. Preprocessing - Remove Anomali Entri"

for filename in tqdm(os.listdir(directory_CSV)):
    print("====" + filename + "====")
    kamus = pd.read_csv(directory_CSV + "/" + filename)
    
    entry_font_size_pos = []
    for i in kamus["entry_font_size_pos"].values.tolist():
        entry_font_size_pos.append(eval(i))
            
    is_prakategorial = kamus["is_padanan_lema"].values.tolist()
            
    kategori_anomali = categorize_anomali_entry(entry_font_size_pos, is_prakategorial)
    kamus["is_anomali"] = kategori_anomali
    
    new_filename = os.path.splitext(filename)[0]
    kamus.to_csv(directory_hasil + "/" + new_filename + "-categorizeAnomali.csv",index=False)
    
#     input_fonts = data["font"].values.tolist()
    
#     if is_contain_bold_and_italic(input_fonts):
#         print("====" + new_filename + "====")
#         CSV_res = build_corpus_one_entry_by_font_pos(data)

#         result_csv = pd.DataFrame.from_dict(CSV_res)
#         result_csv = result_csv[result_csv["Entri"] != ""]
#         result_csv = result_csv.reset_index(drop=True)
#         result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         try:
#             CSV_res = build_corpus_one_entry_by_font_pos(data)

#             result_csv = pd.DataFrame.from_dict(CSV_res)
#             result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         except:
#             print("==== Kamus Gagal ====")
#             print(new_filename)

  0%|          | 0/68 [00:00<?, ?it/s]

====10_Replace.csv====

  1%|▏         | 1/68 [00:03<03:33,  3.18s/it]

====11_Replace.csv====

  3%|▎         | 2/68 [00:05<03:14,  2.95s/it]

====12_Replace.csv====

  4%|▍         | 3/68 [00:10<03:57,  3.66s/it]

====13_Replace.csv====

  6%|▌         | 4/68 [00:12<03:12,  3.01s/it]

====14_Replace.csv====

  7%|▋         | 5/68 [00:15<03:04,  2.92s/it]

====15_Replace.csv====

  9%|▉         | 6/68 [00:17<02:52,  2.78s/it]

====16_Replace.csv====

 10%|█         | 7/68 [00:20<02:56,  2.89s/it]

====17_Replace.csv====

 12%|█▏        | 8/68 [00:22<02:23,  2.39s/it]

====18_Replace.csv====

 13%|█▎        | 9/68 [00:24<02:26,  2.49s/it]

====19_Replace.csv====

 15%|█▍        | 10/68 [00:28<02:46,  2.88s/it]

====1_Replace.csv====

 16%|█▌        | 11/68 [00:31<02:36,  2.75s/it]

====20_Replace.csv====

 18%|█▊        | 12/68 [00:32<02:06,  2.27s/it]

====21_Replace.csv====

 19%|█▉        | 13/68 [00:33<01:49,  2.00s/it]

====22_Replace.csv====

 21%|██        | 14/68 [00:36<02:07,  2.37s/it]

====23_Replace.csv====

 22%|██▏       | 15/68 [00:38<01:50,  2.08s/it]

====24_Replace.csv====

 24%|██▎       | 16/68 [00:41<01:58,  2.28s/it]

====25_Replace.csv====

 25%|██▌       | 17/68 [00:43<02:00,  2.36s/it]

====26_Replace.csv====

 26%|██▋       | 18/68 [00:44<01:39,  1.99s/it]

====27_Replace.csv====

 28%|██▊       | 19/68 [00:45<01:24,  1.72s/it]

====28_Replace.csv====

 29%|██▉       | 20/68 [00:47<01:25,  1.79s/it]

====29_Replace.csv====

 31%|███       | 21/68 [00:48<01:15,  1.61s/it]

====2_Replace.csv====

 32%|███▏      | 22/68 [00:51<01:25,  1.85s/it]

====31_Replace.csv====

 34%|███▍      | 23/68 [00:52<01:17,  1.72s/it]

====32_Replace.csv====

 35%|███▌      | 24/68 [00:54<01:13,  1.67s/it]

====33_Replace.csv====

 37%|███▋      | 25/68 [00:56<01:12,  1.69s/it]

====34_Replace.csv====

 38%|███▊      | 26/68 [00:59<01:30,  2.16s/it]

====35_Replace.csv====

 40%|███▉      | 27/68 [01:01<01:33,  2.27s/it]

====36_Replace.csv====

 41%|████      | 28/68 [01:03<01:24,  2.11s/it]

====37_Replace.csv====

 43%|████▎     | 29/68 [01:05<01:18,  2.00s/it]

====38_Replace.csv====

 44%|████▍     | 30/68 [01:09<01:39,  2.61s/it]

====3_Replace.csv====

 46%|████▌     | 31/68 [01:12<01:45,  2.86s/it]

====41_Replace.csv====

 47%|████▋     | 32/68 [01:16<01:46,  2.96s/it]

====42_Replace.csv====

 49%|████▊     | 33/68 [01:19<01:51,  3.19s/it]

====43_Replace.csv====

 50%|█████     | 34/68 [01:22<01:43,  3.05s/it]

====44_Replace.csv====

 51%|█████▏    | 35/68 [01:23<01:21,  2.45s/it]

====45_Replace.csv====

 53%|█████▎    | 36/68 [01:25<01:15,  2.37s/it]

====46_Replace.csv====

 54%|█████▍    | 37/68 [01:31<01:40,  3.25s/it]

====48_Replace.csv====

 56%|█████▌    | 38/68 [01:31<01:16,  2.55s/it]

====4_Replace.csv====

 57%|█████▋    | 39/68 [01:33<01:07,  2.31s/it]

====50_Replace.csv====

 59%|█████▉    | 40/68 [01:34<00:52,  1.89s/it]

====51_Replace.csv====

 60%|██████    | 41/68 [01:35<00:43,  1.63s/it]

====52_Replace.csv====

 62%|██████▏   | 42/68 [01:37<00:45,  1.76s/it]

====54_Replace.csv====

 63%|██████▎   | 43/68 [01:38<00:36,  1.47s/it]

====55_Replace.csv====

 65%|██████▍   | 44/68 [01:40<00:36,  1.51s/it]

====56_Replace.csv====

 66%|██████▌   | 45/68 [01:42<00:43,  1.91s/it]

====57_Replace.csv====

 68%|██████▊   | 46/68 [01:45<00:48,  2.22s/it]

====58_Replace.csv====

 69%|██████▉   | 47/68 [01:47<00:41,  1.98s/it]

====5_Replace.csv====

 71%|███████   | 48/68 [01:48<00:33,  1.68s/it]

====60_Replace.csv====

 72%|███████▏  | 49/68 [01:51<00:38,  2.02s/it]

====61_Replace.csv====

 74%|███████▎  | 50/68 [01:52<00:34,  1.94s/it]

====62_Replace.csv====

 75%|███████▌  | 51/68 [01:56<00:41,  2.46s/it]

====63_Replace.csv====

 76%|███████▋  | 52/68 [01:58<00:35,  2.24s/it]

====66_Replace.csv====

 78%|███████▊  | 53/68 [01:59<00:28,  1.88s/it]

====67_Replace.csv====

 79%|███████▉  | 54/68 [02:02<00:32,  2.29s/it]

====68_Replace.csv====

 81%|████████  | 55/68 [02:04<00:29,  2.25s/it]

====70_Replace.csv====

 82%|████████▏ | 56/68 [02:04<00:19,  1.66s/it]

====71_Replace.csv====

 84%|████████▍ | 57/68 [02:05<00:14,  1.28s/it]

====77_Replace.csv====

 85%|████████▌ | 58/68 [02:06<00:13,  1.35s/it]

====78_Replace.csv====

 87%|████████▋ | 59/68 [02:07<00:11,  1.24s/it]

====79_Replace.csv====

 88%|████████▊ | 60/68 [02:09<00:11,  1.42s/it]

====84_Replace.csv====

 90%|████████▉ | 61/68 [02:10<00:07,  1.12s/it]

====85_Replace.csv====

 91%|█████████ | 62/68 [02:12<00:08,  1.36s/it]

====87_Replace.csv====

 93%|█████████▎| 63/68 [02:14<00:09,  1.80s/it]

====89_Replace.csv====

 94%|█████████▍| 64/68 [02:15<00:05,  1.40s/it]

====8_Replace.csv====

 96%|█████████▌| 65/68 [02:16<00:03,  1.19s/it]

====91_Replace.csv====

 97%|█████████▋| 66/68 [02:19<00:03,  1.80s/it]

====94_Replace.csv====

 99%|█████████▊| 67/68 [02:20<00:01,  1.71s/it]

====9_Replace.csv====

100%|██████████| 68/68 [02:22<00:00,  2.09s/it]

In [ ]:
directory_hasil = "../../Ekstraksi/4. Preprocessing - Remove Anomali Entri"

result = {
    "nama_kamus" : [],
    "persentasi_anomali":[],
    "jumlah_entri":[]
}

for filename in tqdm(os.listdir(directory_hasil)):
    print("====" + filename + "====")
    kamus = pd.read_csv(directory_hasil + "/" + filename)
    
    entri = kamus["Entri"].values.tolist()
    anomali = kamus["Entri"][kamus["is_anomali"]==1].values.tolist()
    persen_anomali = round((len(anomali)/len(entri))*100,2)
    
    result['nama_kamus'].append(filename)
    result['persentasi_anomali'].append(persen_anomali)
    result['jumlah_entri'].append(len(entri))
    

res_pandas = pd.DataFrame.from_dict(result)
res_pandas.to_csv("../csvAnalysis/exploratory_anomali.csv",index=False)
    
#     input_fonts = data["font"].values.tolist()
    
#     if is_contain_bold_and_italic(input_fonts):
#         print("====" + new_filename + "====")
#         CSV_res = build_corpus_one_entry_by_font_pos(data)

#         result_csv = pd.DataFrame.from_dict(CSV_res)
#         result_csv = result_csv[result_csv["Entri"] != ""]
#         result_csv = result_csv.reset_index(drop=True)
#         result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         try:
#             CSV_res = build_corpus_one_entry_by_font_pos(data)

#             result_csv = pd.DataFrame.from_dict(CSV_res)
#             result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         except:
#             print("==== Kamus Gagal ====")
#             print(new_filename)

  1%|▏         | 1/68 [00:00<00:07,  8.79it/s]

====10_Replace-categorizeAnomali.csv====
====11_Replace-categorizeAnomali.csv====
====12_Replace-categorizeAnomali.csv====

  7%|▋         | 5/68 [00:00<00:07,  8.36it/s]

====13_Replace-categorizeAnomali.csv====
====14_Replace-categorizeAnomali.csv====
====15_Replace-categorizeAnomali.csv====

 10%|█         | 7/68 [00:00<00:07,  8.08it/s]

====16_Replace-categorizeAnomali.csv====
====17_Replace-categorizeAnomali.csv====

 13%|█▎        | 9/68 [00:01<00:07,  8.29it/s]

====18_Replace-categorizeAnomali.csv====
====19_Replace-categorizeAnomali.csv====

 16%|█▌        | 11/68 [00:01<00:07,  7.33it/s]

====1_Replace-categorizeAnomali.csv====
====20_Replace-categorizeAnomali.csv====
====21_Replace-categorizeAnomali.csv====

 21%|██        | 14/68 [00:01<00:06,  8.82it/s]

====22_Replace-categorizeAnomali.csv====
====23_Replace-categorizeAnomali.csv====
====24_Replace-categorizeAnomali.csv====

 25%|██▌       | 17/68 [00:02<00:06,  8.14it/s]

====25_Replace-categorizeAnomali.csv====
====26_Replace-categorizeAnomali.csv====

 28%|██▊       | 19/68 [00:02<00:05,  9.73it/s]

====27_Replace-categorizeAnomali.csv====
====28_Replace-categorizeAnomali.csv====
====29_Replace-categorizeAnomali.csv====

 34%|███▍      | 23/68 [00:02<00:04, 10.46it/s]

====2_Replace-categorizeAnomali.csv====
====31_Replace-categorizeAnomali.csv====
====32_Replace-categorizeAnomali.csv====

 37%|███▋      | 25/68 [00:02<00:04,  9.73it/s]

====33_Replace-categorizeAnomali.csv====
====34_Replace-categorizeAnomali.csv====

 40%|███▉      | 27/68 [00:03<00:04,  8.57it/s]

====35_Replace-categorizeAnomali.csv====
====36_Replace-categorizeAnomali.csv====
====37_Replace-categorizeAnomali.csv====

 44%|████▍     | 30/68 [00:03<00:04,  8.50it/s]

====38_Replace-categorizeAnomali.csv====
====3_Replace-categorizeAnomali.csv====

 47%|████▋     | 32/68 [00:03<00:04,  7.32it/s]

====41_Replace-categorizeAnomali.csv====
====42_Replace-categorizeAnomali.csv====

 50%|█████     | 34/68 [00:04<00:05,  6.75it/s]

====43_Replace-categorizeAnomali.csv====
====44_Replace-categorizeAnomali.csv====
====45_Replace-categorizeAnomali.csv====

 53%|█████▎    | 36/68 [00:04<00:03,  8.19it/s]

====46_Replace-categorizeAnomali.csv====

 57%|█████▋    | 39/68 [00:04<00:03,  8.05it/s]

====48_Replace-categorizeAnomali.csv====
====4_Replace-categorizeAnomali.csv====
====50_Replace-categorizeAnomali.csv====
====51_Replace-categorizeAnomali.csv====

 63%|██████▎   | 43/68 [00:04<00:02, 10.81it/s]

====52_Replace-categorizeAnomali.csv====
====54_Replace-categorizeAnomali.csv====
====55_Replace-categorizeAnomali.csv====

 66%|██████▌   | 45/68 [00:05<00:02,  9.68it/s]

====56_Replace-categorizeAnomali.csv====
====57_Replace-categorizeAnomali.csv====

 69%|██████▉   | 47/68 [00:05<00:02,  9.58it/s]

====58_Replace-categorizeAnomali.csv====
====5_Replace-categorizeAnomali.csv====
====60_Replace-categorizeAnomali.csv====

 72%|███████▏  | 49/68 [00:05<00:01,  9.71it/s]

====61_Replace-categorizeAnomali.csv====
====62_Replace-categorizeAnomali.csv====

 76%|███████▋  | 52/68 [00:06<00:01,  8.11it/s]

====63_Replace-categorizeAnomali.csv====
====66_Replace-categorizeAnomali.csv====

 79%|███████▉  | 54/68 [00:06<00:01,  8.15it/s]

====67_Replace-categorizeAnomali.csv====
====68_Replace-categorizeAnomali.csv====

 85%|████████▌ | 58/68 [00:06<00:00, 11.20it/s]

====70_Replace-categorizeAnomali.csv====
====71_Replace-categorizeAnomali.csv====
====77_Replace-categorizeAnomali.csv====
====78_Replace-categorizeAnomali.csv====
====79_Replace-categorizeAnomali.csv====

 91%|█████████ | 62/68 [00:06<00:00, 13.37it/s]

====84_Replace-categorizeAnomali.csv====
====85_Replace-categorizeAnomali.csv====
====87_Replace-categorizeAnomali.csv====

 94%|█████████▍| 64/68 [00:07<00:00, 11.07it/s]

====89_Replace-categorizeAnomali.csv====
====8_Replace-categorizeAnomali.csv====
====91_Replace-categorizeAnomali.csv====

100%|██████████| 68/68 [00:07<00:00,  9.09it/s]

====94_Replace-categorizeAnomali.csv====
====9_Replace-categorizeAnomali.csv====

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
0   10_Replace-categorizeAnomali.csv               27.12          5287
1   11_Replace-categorizeAnomali.csv               81.16          2298
2   12_Replace-categorizeAnomali.csv               33.20          9411
3   13_Replace-categorizeAnomali.csv               62.24          1025
4   14_Replace-categorizeAnomali.csv               61.61          1258
5   15_Replace-categorizeAnomali.csv               70.40          1500
6   16_Replace-categorizeAnomali.csv               37.34          4108
7   17_Replace-categorizeAnomali.csv               98.15          2161
8   18_Replace-categorizeAnomali.csv               32.94         14890
9   19_Replace-categorizeAnomali.csv               26.83          8562
10   1_Replace-categorizeAnomali.csv               98.53          4024
11  20_Replace-categorizeAnomali.csv               99.81          2109
12  21_Replace-categorizeAnomali.csv               48.28          2997
13  22_Replace-categorizeAnomali.csv               96.72           366
14  23_Replace-categorizeAnomali.csv               35.74          2938
15  24_Replace-categorizeAnomali.csv               46.45          8517
16  25_Replace-categorizeAnomali.csv               61.82           440
17  26_Replace-categorizeAnomali.csv               16.21          4743
18  27_Replace-categorizeAnomali.csv               56.84          3728
19  28_Replace-categorizeAnomali.csv               38.17          1082
20  29_Replace-categorizeAnomali.csv               99.75          1980
21   2_Replace-categorizeAnomali.csv               97.81          4752
22  31_Replace-categorizeAnomali.csv               99.12          1371
23  32_Replace-categorizeAnomali.csv               99.23          3365
24  33_Replace-categorizeAnomali.csv               90.14          2912
25  34_Replace-categorizeAnomali.csv               47.98         11225
26  35_Replace-categorizeAnomali.csv               27.50          3146
27  36_Replace-categorizeAnomali.csv               48.42          2792
28  37_Replace-categorizeAnomali.csv               65.10           361
29  38_Replace-categorizeAnomali.csv               93.50          4372
30   3_Replace-categorizeAnomali.csv               96.52           834
31  41_Replace-categorizeAnomali.csv               40.45         13390
32  42_Replace-categorizeAnomali.csv               38.00          6931
33  43_Replace-categorizeAnomali.csv               29.75          4917
34  44_Replace-categorizeAnomali.csv               98.85          2002
35  45_Replace-categorizeAnomali.csv               33.52          3664
36  46_Replace-categorizeAnomali.csv               34.13         13239
37  48_Replace-categorizeAnomali.csv               94.42           233
38   4_Replace-categorizeAnomali.csv               27.70          3213
39  50_Replace-categorizeAnomali.csv               73.33          1620
40  51_Replace-categorizeAnomali.csv               82.82          2095
41  52_Replace-categorizeAnomali.csv               98.99          2682
42  54_Replace-categorizeAnomali.csv               53.78          2356
43  55_Replace-categorizeAnomali.csv               42.62          2668
44  56_Replace-categorizeAnomali.csv               98.85          3119
45  57_Replace-categorizeAnomali.csv               98.11          2650
46  58_Replace-categorizeAnomali.csv               98.82          5255
47   5_Replace-categorizeAnomali.csv               17.59          3854
48  60_Replace-categorizeAnomali.csv               86.56          1644
49  61_Replace-categorizeAnomali.csv               99.11          2795
50  62_Replace-categorizeAnomali.csv               98.42          8799
51  63_Replace-categorizeAnomali.csv               66.08          1085
52  66_Replace-categorizeAnomali.csv               99.10          1661
53  67_Replace-categorizeAnomali.csv               94.10          3135
54  68_Replace-categorizeAnomali.csv                8.04          7546
55  70_Replace-categorizeAnomali.csv               55.08           354
56  71_Replace-categorizeAnomali.csv               12.83           904
57  77_Replace-categorizeAnomali.csv               23.29          1782
58  78_Replace-categorizeAnomali.csv               99.16          1196
59  79_Replace-categorizeAnomali.csv               59.40          1877
60  84_Replace-categorizeAnomali.csv               99.10          1001
61  85_Replace-categorizeAnomali.csv               94.93          1243
62  87_Replace-categorizeAnomali.csv               66.48          2315
63  89_Replace-categorizeAnomali.csv                2.17          1153
64   8_Replace-categorizeAnomali.csv               84.75          2282
65  91_Replace-categorizeAnomali.csv                7.91         10852
66  94_Replace-categorizeAnomali.csv               94.36           958
67   9_Replace-categorizeAnomali.csv               97.29          2248

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 50]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
1   11_Replace-categorizeAnomali.csv               81.16          2298
3   13_Replace-categorizeAnomali.csv               62.24          1025
4   14_Replace-categorizeAnomali.csv               61.61          1258
5   15_Replace-categorizeAnomali.csv               70.40          1500
7   17_Replace-categorizeAnomali.csv               98.15          2161
10   1_Replace-categorizeAnomali.csv               98.53          4024
11  20_Replace-categorizeAnomali.csv               99.81          2109
13  22_Replace-categorizeAnomali.csv               96.72           366
16  25_Replace-categorizeAnomali.csv               61.82           440
18  27_Replace-categorizeAnomali.csv               56.84          3728
20  29_Replace-categorizeAnomali.csv               99.75          1980
21   2_Replace-categorizeAnomali.csv               97.81          4752
22  31_Replace-categorizeAnomali.csv               99.12          1371
23  32_Replace-categorizeAnomali.csv               99.23          3365
24  33_Replace-categorizeAnomali.csv               90.14          2912
28  37_Replace-categorizeAnomali.csv               65.10           361
29  38_Replace-categorizeAnomali.csv               93.50          4372
30   3_Replace-categorizeAnomali.csv               96.52           834
34  44_Replace-categorizeAnomali.csv               98.85          2002
37  48_Replace-categorizeAnomali.csv               94.42           233
39  50_Replace-categorizeAnomali.csv               73.33          1620
40  51_Replace-categorizeAnomali.csv               82.82          2095
41  52_Replace-categorizeAnomali.csv               98.99          2682
42  54_Replace-categorizeAnomali.csv               53.78          2356
44  56_Replace-categorizeAnomali.csv               98.85          3119
45  57_Replace-categorizeAnomali.csv               98.11          2650
46  58_Replace-categorizeAnomali.csv               98.82          5255
48  60_Replace-categorizeAnomali.csv               86.56          1644
49  61_Replace-categorizeAnomali.csv               99.11          2795
50  62_Replace-categorizeAnomali.csv               98.42          8799
51  63_Replace-categorizeAnomali.csv               66.08          1085
52  66_Replace-categorizeAnomali.csv               99.10          1661
53  67_Replace-categorizeAnomali.csv               94.10          3135
55  70_Replace-categorizeAnomali.csv               55.08           354
58  78_Replace-categorizeAnomali.csv               99.16          1196
59  79_Replace-categorizeAnomali.csv               59.40          1877
60  84_Replace-categorizeAnomali.csv               99.10          1001
61  85_Replace-categorizeAnomali.csv               94.93          1243
62  87_Replace-categorizeAnomali.csv               66.48          2315
64   8_Replace-categorizeAnomali.csv               84.75          2282
66  94_Replace-categorizeAnomali.csv               94.36           958
67   9_Replace-categorizeAnomali.csv               97.29          2248

(42, 3)

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] < 90]
data = data[data["persentasi_anomali"] > 50]
data = data.sort_values(by=["persentasi_anomali"], ascending=False) 
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")
data.to_csv("top5090%.csv",index=False)

                          nama_kamus  persentasi_anomali  jumlah_entri
48  60_Replace-categorizeAnomali.csv               86.56          1644
64   8_Replace-categorizeAnomali.csv               84.75          2282
40  51_Replace-categorizeAnomali.csv               82.82          2095
1   11_Replace-categorizeAnomali.csv               81.16          2298
39  50_Replace-categorizeAnomali.csv               73.33          1620
5   15_Replace-categorizeAnomali.csv               70.40          1500
62  87_Replace-categorizeAnomali.csv               66.48          2315
51  63_Replace-categorizeAnomali.csv               66.08          1085
28  37_Replace-categorizeAnomali.csv               65.10           361
3   13_Replace-categorizeAnomali.csv               62.24          1025
16  25_Replace-categorizeAnomali.csv               61.82           440
4   14_Replace-categorizeAnomali.csv               61.61          1258
59  79_Replace-categorizeAnomali.csv               59.40          1877
18  27_Replace-categorizeAnomali.csv               56.84          3728
55  70_Replace-categorizeAnomali.csv               55.08           354
42  54_Replace-categorizeAnomali.csv               53.78          2356

(16, 3)

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 90]
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")
data.to_csv("top90%.csv",index=False)

                          nama_kamus  persentasi_anomali  jumlah_entri
11  20_Replace-categorizeAnomali.csv               99.81          2109
20  29_Replace-categorizeAnomali.csv               99.75          1980
23  32_Replace-categorizeAnomali.csv               99.23          3365
58  78_Replace-categorizeAnomali.csv               99.16          1196
22  31_Replace-categorizeAnomali.csv               99.12          1371
49  61_Replace-categorizeAnomali.csv               99.11          2795
60  84_Replace-categorizeAnomali.csv               99.10          1001
52  66_Replace-categorizeAnomali.csv               99.10          1661
41  52_Replace-categorizeAnomali.csv               98.99          2682
44  56_Replace-categorizeAnomali.csv               98.85          3119
34  44_Replace-categorizeAnomali.csv               98.85          2002
46  58_Replace-categorizeAnomali.csv               98.82          5255
10   1_Replace-categorizeAnomali.csv               98.53          4024
50  62_Replace-categorizeAnomali.csv               98.42          8799
7   17_Replace-categorizeAnomali.csv               98.15          2161
45  57_Replace-categorizeAnomali.csv               98.11          2650
21   2_Replace-categorizeAnomali.csv               97.81          4752
67   9_Replace-categorizeAnomali.csv               97.29          2248
13  22_Replace-categorizeAnomali.csv               96.72           366
30   3_Replace-categorizeAnomali.csv               96.52           834
61  85_Replace-categorizeAnomali.csv               94.93          1243
37  48_Replace-categorizeAnomali.csv               94.42           233
66  94_Replace-categorizeAnomali.csv               94.36           958
53  67_Replace-categorizeAnomali.csv               94.10          3135
29  38_Replace-categorizeAnomali.csv               93.50          4372
24  33_Replace-categorizeAnomali.csv               90.14          2912

(26, 3)

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 80]
data = data[data["persentasi_anomali"] <= 90]
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
48  60_Replace-categorizeAnomali.csv               86.56          1644
64   8_Replace-categorizeAnomali.csv               84.75          2282
40  51_Replace-categorizeAnomali.csv               82.82          2095
1   11_Replace-categorizeAnomali.csv               81.16          2298

(4, 3)

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 0]
data = data[data["persentasi_anomali"] <= 30]
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
33  43_Replace-categorizeAnomali.csv               29.75          4917
38   4_Replace-categorizeAnomali.csv               27.70          3213
26  35_Replace-categorizeAnomali.csv               27.50          3146
0   10_Replace-categorizeAnomali.csv               27.12          5287
9   19_Replace-categorizeAnomali.csv               26.83          8562
57  77_Replace-categorizeAnomali.csv               23.29          1782
47   5_Replace-categorizeAnomali.csv               17.59          3854
17  26_Replace-categorizeAnomali.csv               16.21          4743
56  71_Replace-categorizeAnomali.csv               12.83           904
54  68_Replace-categorizeAnomali.csv                8.04          7546
65  91_Replace-categorizeAnomali.csv                7.91         10852
63  89_Replace-categorizeAnomali.csv                2.17          1153

(12, 3)

In [ ]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../../csvAnalysis/exploratory_anomali.csv")
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
11  20_Replace-categorizeAnomali.csv               99.81          2109
20  29_Replace-categorizeAnomali.csv               99.75          1980
23  32_Replace-categorizeAnomali.csv               99.23          3365
58  78_Replace-categorizeAnomali.csv               99.16          1196
22  31_Replace-categorizeAnomali.csv               99.12          1371
49  61_Replace-categorizeAnomali.csv               99.11          2795
60  84_Replace-categorizeAnomali.csv               99.10          1001
52  66_Replace-categorizeAnomali.csv               99.10          1661
41  52_Replace-categorizeAnomali.csv               98.99          2682
34  44_Replace-categorizeAnomali.csv               98.85          2002
44  56_Replace-categorizeAnomali.csv               98.85          3119
46  58_Replace-categorizeAnomali.csv               98.82          5255
10   1_Replace-categorizeAnomali.csv               98.53          4024
50  62_Replace-categorizeAnomali.csv               98.42          8799
7   17_Replace-categorizeAnomali.csv               98.15          2161
45  57_Replace-categorizeAnomali.csv               98.11          2650
21   2_Replace-categorizeAnomali.csv               97.81          4752
67   9_Replace-categorizeAnomali.csv               97.29          2248
13  22_Replace-categorizeAnomali.csv               96.72           366
30   3_Replace-categorizeAnomali.csv               96.52           834
61  85_Replace-categorizeAnomali.csv               94.93          1243
37  48_Replace-categorizeAnomali.csv               94.42           233
66  94_Replace-categorizeAnomali.csv               94.36           958
53  67_Replace-categorizeAnomali.csv               94.10          3135
29  38_Replace-categorizeAnomali.csv               93.50          4372
24  33_Replace-categorizeAnomali.csv               90.14          2912
48  60_Replace-categorizeAnomali.csv               86.56          1644
64   8_Replace-categorizeAnomali.csv               84.75          2282
40  51_Replace-categorizeAnomali.csv               82.82          2095
1   11_Replace-categorizeAnomali.csv               81.16          2298
39  50_Replace-categorizeAnomali.csv               73.33          1620
5   15_Replace-categorizeAnomali.csv               70.40          1500
62  87_Replace-categorizeAnomali.csv               66.48          2315
51  63_Replace-categorizeAnomali.csv               66.08          1085
28  37_Replace-categorizeAnomali.csv               65.10           361
3   13_Replace-categorizeAnomali.csv               62.24          1025
16  25_Replace-categorizeAnomali.csv               61.82           440
4   14_Replace-categorizeAnomali.csv               61.61          1258
59  79_Replace-categorizeAnomali.csv               59.40          1877
18  27_Replace-categorizeAnomali.csv               56.84          3728
55  70_Replace-categorizeAnomali.csv               55.08           354
42  54_Replace-categorizeAnomali.csv               53.78          2356
27  36_Replace-categorizeAnomali.csv               48.42          2792
12  21_Replace-categorizeAnomali.csv               48.28          2997
25  34_Replace-categorizeAnomali.csv               47.98         11225
15  24_Replace-categorizeAnomali.csv               46.45          8517
43  55_Replace-categorizeAnomali.csv               42.62          2668
31  41_Replace-categorizeAnomali.csv               40.45         13390
19  28_Replace-categorizeAnomali.csv               38.17          1082
32  42_Replace-categorizeAnomali.csv               38.00          6931
6   16_Replace-categorizeAnomali.csv               37.34          4108
14  23_Replace-categorizeAnomali.csv               35.74          2938
36  46_Replace-categorizeAnomali.csv               34.13         13239
35  45_Replace-categorizeAnomali.csv               33.52          3664
2   12_Replace-categorizeAnomali.csv               33.20          9411
8   18_Replace-categorizeAnomali.csv               32.94         14890
33  43_Replace-categorizeAnomali.csv               29.75          4917
38   4_Replace-categorizeAnomali.csv               27.70          3213
26  35_Replace-categorizeAnomali.csv               27.50          3146
0   10_Replace-categorizeAnomali.csv               27.12          5287
9   19_Replace-categorizeAnomali.csv               26.83          8562
57  77_Replace-categorizeAnomali.csv               23.29          1782
47   5_Replace-categorizeAnomali.csv               17.59          3854
17  26_Replace-categorizeAnomali.csv               16.21          4743
56  71_Replace-categorizeAnomali.csv               12.83           904
54  68_Replace-categorizeAnomali.csv                8.04          7546
65  91_Replace-categorizeAnomali.csv                7.91         10852
63  89_Replace-categorizeAnomali.csv                2.17          1153

(68, 3)