# PostProcessing pyspellchecker (Billex & Morphology)

Companion to `PostProcessing pyspellchecker.ipynb`, which only handles the
Parallel Corpus. This notebook applies the same `pyspellchecker` pipeline,
with the same Indonesian dictionary, to the **other two NLP resources**:

- **Bilingual Lexicon** (`9. Bilingual Lexicon - Fixed/*_Billex.csv`)
- **Morphology** (`10. Morphology - Fixed/*_Morphology.csv`)

## Which column gets corrected?

`LookupIsFromIndonesia.csv` says whether each dictionary is Indonesian→Regional
(`is_from_indonesia=1`) or Regional to Indonesian (`is_from_indonesia=0`). Only
the **Indonesian** side is run through the spellchecker; the regional side is
left untouched because the Indonesian lexicon would falsely "correct" perfectly
valid regional words.

| Resource    | dir=1 (Ind→Reg) Indonesian column(s) | dir=0 (Reg→Ind) Indonesian column(s) |
|-------------|--------------------------------------|--------------------------------------|
| Billex      | `kata_asal`                          | `kata_tujuan`                        |
| Morphology  | `kata` and `form`                    | *(skipped — see below)*              |

**Why Morphology dir=0 is skipped.** When the source dictionary is
Regional to Indonesian, the morphology pipeline stores the **regional** derived
form in the `form` column and the **regional** headword in `kata`. The
Indonesian glosses live in `makna` upstream and aren't carried into the
Morphology resource. Running the spellchecker on regional words would corrupt
them. These rows are passed through unchanged.

## Outputs

- `../Ekstraksi/13. Bilingual Lexicon - Spelling Checker/<id>_Billex.csv`
- `../Ekstraksi/13. Bilingual Lexicon - Spelling Checker/<id>_Billex_audit.csv`
- `../Ekstraksi/14. Morphology - Spelling Checker/<id>_Morphology.csv`
- `../Ekstraksi/14. Morphology - Spelling Checker/<id>_Morphology_audit.csv`
- `_billex_summary.csv` / `_morph_summary.csv` — per-dict correction counts

## 1. Imports & paths

In [28]:
import os
import re
import sys
from pathlib import Path
from typing import Optional

import pandas as pd
from spellchecker import SpellChecker
import concurrent.futures

# Reuse the same helpers used by the morphology / billex / parcor fix scripts
sys.path.insert(0, str(Path('.').resolve()))
from _common import (
    parse_dict_id,
    load_direction_lookup,
    direction_for,
    roles_for_billex,
    roles_for_morphology,
)

# Input directories — same as PostProcessing pyspellchecker.ipynb uses
BILLEX_SRC = Path('../Ekstraksi/9. (New) Bilingual Lexicon - Fixed')
MORPH_SRC  = Path('../Ekstraksi/10. (New) Morphology - Fixed')

# Output directories — sit alongside `12. Parallel Corpus - Spelling Checker`
BILLEX_DST = Path('../Ekstraksi/13. (New) Bilingual Lexicon - Spellcheck Detection/dict_strategy_C')
MORPH_DST  = Path('../Ekstraksi/14. (New) Morphology - Spellcheck Detection/dict_strategy_C')

BILLEX_DST.mkdir(parents=True, exist_ok=True)
MORPH_DST.mkdir(parents=True, exist_ok=True)

assert BILLEX_SRC.exists(), f'Billex source dir not found: {BILLEX_SRC.resolve()}'
assert MORPH_SRC.exists(),  f'Morph source dir not found:  {MORPH_SRC.resolve()}'

print(f'Reading Billex from: {BILLEX_SRC.resolve()}')
print(f'Reading Morph  from: {MORPH_SRC.resolve()}')
print(f'Writing Billex to:   {BILLEX_DST.resolve()}')
print(f'Writing Morph  to:   {MORPH_DST.resolve()}')

Reading Billex from: C:\Users\Legion\OneDrive\Documents\UNI\TA\tugas-akhir-data-mining\TAEkstraksiKamus\Ekstraksi\9. (New) Bilingual Lexicon - Fixed
Reading Morph  from: C:\Users\Legion\OneDrive\Documents\UNI\TA\tugas-akhir-data-mining\TAEkstraksiKamus\Ekstraksi\10. (New) Morphology - Fixed
Writing Billex to:   C:\Users\Legion\OneDrive\Documents\UNI\TA\tugas-akhir-data-mining\TAEkstraksiKamus\Ekstraksi\13. (New) Bilingual Lexicon - Spellcheck Detection\dict_strategy_C
Writing Morph  to:   C:\Users\Legion\OneDrive\Documents\UNI\TA\tugas-akhir-data-mining\TAEkstraksiKamus\Ekstraksi\14. (New) Morphology - Spellcheck Detection\dict_strategy_C

## 2. Load the Indonesian spellchecker dictionary

Identical to the Parcor notebook: same dictionary, same `pyspellchecker`
configuration. Swap `DICT_PATH` between the three strategies (A baseline,
B all-tier-eligible, C ≥3-dict-frequency) the same way you would for Parcor.

Loading the dictionary once at module level keeps the spellchecker stateless
across threads.

In [29]:
lookup_df = pd.read_csv('../Ekstraksi/12. Parallel Corpus - Spelling Checker/LookupIsFromIndonesia.csv')

spell = SpellChecker(language=None)
# DICT_PATH = '../spellCheckDicts/vocab_strategies_v3_1/dict_strategy_original.json'
# DICT_PATH = '../spellCheckDicts/vocab_strategies_v3_1/dict_strategy_B.json'
DICT_PATH = '../spellCheckDicts/vocab_strategies_v3_1/dict_strategy_C.json'

if os.path.exists(DICT_PATH):
    spell.word_frequency.load_dictionary(DICT_PATH)
    print(f'Loaded JSON dictionary from {DICT_PATH}')
else:
    raise FileNotFoundError(
        f"Custom dictionary not found at '{DICT_PATH}'. "
        'Check that the working directory is correct before running.'
    )

# Direction lookup keyed by dict_id (reused for both resources)
DIRECTION = load_direction_lookup()
print(f'Loaded direction for {len(DIRECTION)} dictionaries')

Loaded JSON dictionary from ../spellCheckDicts/vocab_strategies_v3_1/dict_strategy_C.json
Loaded direction for 82 dictionaries

## 3. Core spellchecker helpers

`fix_word` and `fix_sentence` are lifted directly from
`PostProcessing pyspellchecker.ipynb` so the correction behaviour is
**identical** to what was applied to Parcor, same case-preservation, same
`spell.unknown` gate, same `spell.correction` call.

`fix_word` is exposed separately because Billex/Morph cells are typically
single tokens, not sentences. `fix_sentence` is kept for cells that contain
multi-word headwords (Billex sometimes has these, e.g. `"abdi dalem"`).

In [30]:
def fix_word(word: str) -> str:
    """Correct a single token, preserving original case."""
    if not word or not word.isalpha():
        return word
    lower_word = word.lower()
    if lower_word in spell.unknown([lower_word]):
        correction = spell.correction(lower_word)
        if correction and correction != lower_word:
            if word.istitle():
                return correction.capitalize()
            elif word.isupper():
                return correction.upper()
            else:
                return correction
    return word


def fix_sentence(sentence) -> str:
    """Run the spellchecker over every alphabetic run in a string."""
    def replace(match):
        word = match.group(0)
        lower_word = word.lower()
        if lower_word in spell.unknown([lower_word]):
            correction = spell.correction(lower_word)
            if correction and correction != lower_word:
                if word.istitle():
                    return correction.capitalize()
                elif word.isupper():
                    return correction.upper()
                else:
                    return correction
        return word
    return re.sub(r'[A-Za-z]+', replace, str(sentence))


def fix_cell(value) -> str:
    """
    Spellcheck a Billex / Morphology cell. Single-word cells go through
    `fix_word` so we never insert spurious whitespace; multi-word cells fall
    back to `fix_sentence` so each token is treated independently.
    """
    if pd.isna(value):
        return value
    s = str(value)
    if not s.strip():
        return s
    # Single alphabetic token? use fix_word for cleanest case handling.
    if re.fullmatch(r"[A-Za-z]+", s.strip()):
        return fix_word(s.strip()) if s == s.strip() else s.replace(s.strip(), fix_word(s.strip()))
    return fix_sentence(s)

## 4. Direction lookup wrapper

Mirrors `get_is_from_indonesia` from the Parcor notebook so the file-name to
direction resolution is consistent across all three resources. Returns
`(success, is_from_indonesia)` to match the original signature.

In [31]:
def get_is_from_indonesia(input_path) -> tuple[bool, int]:
    filename = os.path.basename(str(input_path))
    file_id = parse_dict_id(filename)
    if file_id is None:
        return False, -1
    if file_id in DIRECTION:
        return True, DIRECTION[file_id]
    return False, -1


# Sanity check on a few known dicts
for fname in ['4_Billex.csv', '18_Morphology.csv', '24_Billex.csv']:
    print(f'  {fname:<22} -> {get_is_from_indonesia(fname)}')

  4_Billex.csv           -> (True, 1)
  18_Morphology.csv      -> (True, 0)
  24_Billex.csv          -> (True, 0)

## 5. Billex processor

For each `<id>_Billex.csv`:

1. Look up direction: know which column is Indonesian.
2. Spellcheck every cell in the Indonesian column.
3. Leave the regional column and `makna` untouched.
4. Write the pipeline-compatible CSV and a tracking audit CSV.

The audit file keeps the original column under `<col>_original` and adds a
boolean `<col>_corrected` flag so downstream evaluation can quantify how much
the spellchecker actually changed.

In [32]:
def process_billex(file_name: str) -> str:
    try:
        input_file  = BILLEX_SRC / file_name
        output_file = BILLEX_DST / file_name
        audit_file  = BILLEX_DST / file_name.replace('.csv', '_audit.csv')

        # Skip audit files coming in from the upstream stage — we'll write our own.
        if file_name.endswith('_audit.csv'):
            return f'Skip: {file_name} (audit file from upstream)'

        success, is_from_indonesia = get_is_from_indonesia(input_file)
        if not success:
            return f'Skip: No matching ID for {file_name}'

        df = pd.read_csv(input_file)
        if 'kata_asal' not in df.columns or 'kata_tujuan' not in df.columns:
            return f'Skip: {file_name} missing kata_asal/kata_tujuan'

        ind_col, _ = roles_for_billex(is_from_indonesia)

        original = df[ind_col].astype(str).where(df[ind_col].notna(), '')
        corrected = original.apply(fix_cell)

        # Pipeline-compatible output: only the standard columns
        out_df = df.copy()
        out_df[ind_col] = corrected
        # Preserve same column order as input
        out_df.to_csv(output_file, index=False)

        # Audit CSV: original + corrected + flag
        audit_df = df.copy()
        audit_df[f'{ind_col}_original']  = original
        audit_df[ind_col]                = corrected
        audit_df[f'{ind_col}_corrected'] = original != corrected
        audit_df['direction']            = is_from_indonesia
        audit_df.to_csv(audit_file, index=False)

        n_changed = int((original != corrected).sum())
        return f'Processed: {file_name} ({len(out_df)} rows, {n_changed} corrections in {ind_col})'

    except Exception as e:
        return f'Error in {file_name}: {e}'


billex_files = [
    f for f in os.listdir(BILLEX_SRC)
    if f.endswith('.csv') and not f.endswith('_audit.csv')
    and not f.startswith('_')
]
print(f'Found {len(billex_files)} Billex files to process')

billex_results = []
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
    futures = [executor.submit(process_billex, f) for f in billex_files]
    for count, future in enumerate(concurrent.futures.as_completed(futures), 1):
        msg = future.result()
        billex_results.append(msg)
        print(f'[{count}/{len(billex_files)}] {msg}')

Found 82 Billex files to process
[1/82] Processed: 13_Billex.csv (412 rows, 130 corrections in kata_asal)
[2/82] Processed: 11_Billex.csv (4896 rows, 525 corrections in kata_tujuan)
[3/82] Processed: 17_Billex.csv (1161 rows, 157 corrections in kata_tujuan)
[4/82] Processed: 16_Billex.csv (2044 rows, 948 corrections in kata_asal)
[5/82] Processed: 15_Billex.csv (2800 rows, 1190 corrections in kata_asal)
[6/82] Processed: 20_Billex.csv (1761 rows, 35 corrections in kata_tujuan)
[7/82] Processed: 18_Billex.csv (9116 rows, 1359 corrections in kata_tujuan)
[8/82] Processed: 22_Billex.csv (2224 rows, 114 corrections in kata_tujuan)
[9/82] Processed: 1_Billex.csv (2343 rows, 410 corrections in kata_tujuan)
[10/82] Processed: 0_Billex.csv (2328 rows, 1265 corrections in kata_asal)
[11/82] Processed: 23_Billex.csv (2001 rows, 345 corrections in kata_tujuan)
[12/82] Processed: 10_Billex.csv (4356 rows, 2572 corrections in kata_asal)
[13/82] Processed: 21_Billex.csv (1686 rows, 702 corrections in kata_asal)
[14/82] Processed: 24_Billex.csv (5403 rows, 1661 corrections in kata_tujuan)
[15/82] Processed: 25_Billex.csv (2931 rows, 1346 corrections in kata_asal)
[16/82] Processed: 28_Billex.csv (5631 rows, 572 corrections in kata_tujuan)
[17/82] Processed: 31_Billex.csv (336 rows, 40 corrections in kata_tujuan)
[18/82] Processed: 14_Billex.csv (6112 rows, 3242 corrections in kata_asal)
[19/82] Processed: 29_Billex.csv (1203 rows, 122 corrections in kata_tujuan)
[20/82] Processed: 32_Billex.csv (1991 rows, 169 corrections in kata_tujuan)
[21/82] Processed: 2_Billex.csv (3246 rows, 382 corrections in kata_tujuan)
[22/82] Processed: 33_Billex.csv (1903 rows, 286 corrections in kata_tujuan)
[23/82] Processed: 27_Billex.csv (2664 rows, 1373 corrections in kata_asal)
[24/82] Processed: 26_Billex.csv (3639 rows, 1878 corrections in kata_asal)
[25/82] Processed: 39_Billex.csv (2580 rows, 348 corrections in kata_tujuan)
[26/82] Processed: 3_Billex.csv (1594 rows, 105 corrections in kata_tujuan)
[27/82] Processed: 38_Billex.csv (1756 rows, 814 corrections in kata_asal)
[28/82] Processed: 37_Billex.csv (2694 rows, 1239 corrections in kata_asal)
[29/82] Processed: 35_Billex.csv (3679 rows, 1666 corrections in kata_asal)
[30/82] Processed: 19_Billex.csv (12796 rows, 6613 corrections in kata_asal)
[31/82] Processed: 44_Billex.csv (2454 rows, 162 corrections in kata_tujuan)
[32/82] Processed: 36_Billex.csv (3078 rows, 1273 corrections in kata_asal)
[33/82] Skip: No matching ID for 47_Billex.csv
[34/82] Processed: 48_Billex.csv (928 rows, 136 corrections in kata_tujuan)
[35/82] Processed: 34_Billex.csv (5448 rows, 2795 corrections in kata_asal)
[36/82] Processed: 50_Billex.csv (525 rows, 322 corrections in kata_asal)
[37/82] Processed: 51_Billex.csv (1094 rows, 161 corrections in kata_tujuan)
[38/82] Processed: 52_Billex.csv (1741 rows, 259 corrections in kata_tujuan)
[39/82] Processed: 53_Billex.csv (91 rows, 16 corrections in kata_tujuan)
[40/82] Processed: 46_Billex.csv (10675 rows, 1714 corrections in kata_tujuan)
[41/82] Processed: 54_Billex.csv (1281 rows, 698 corrections in kata_asal)
[42/82] Processed: 45_Billex.csv (2981 rows, 1376 corrections in kata_asal)
[43/82] Processed: 56_Billex.csv (1759 rows, 348 corrections in kata_tujuan)
[44/82] Processed: 58_Billex.csv (763 rows, 128 corrections in kata_tujuan)
[45/82] Processed: 4_Billex.csv (2986 rows, 1425 corrections in kata_asal)
[46/82] Processed: 57_Billex.csv (3686 rows, 501 corrections in kata_tujuan)
[47/82] Processed: 60_Billex.csv (1136 rows, 128 corrections in kata_tujuan)
[48/82] Processed: 12_Billex.csv (6406 rows, 2421 corrections in kata_asal)
[49/82] Processed: 62_Billex.csv (777 rows, 116 corrections in kata_tujuan)
[50/82] Processed: 61_Billex.csv (940 rows, 169 corrections in kata_tujuan)
[51/82] Processed: 64_Billex.csv (2279 rows, 290 corrections in kata_tujuan)
[52/82] Processed: 66_Billex.csv (976 rows, 148 corrections in kata_tujuan)
[53/82] Processed: 55_Billex.csv (1825 rows, 973 corrections in kata_asal)
[54/82] Processed: 65_Billex.csv (4002 rows, 716 corrections in kata_tujuan)
[55/82] Processed: 43_Billex.csv (5065 rows, 2618 corrections in kata_asal)
[56/82] Processed: 71_Billex.csv (784 rows, 22 corrections in kata_tujuan)
[57/82] Processed: 69_Billex.csv (1205 rows, 114 corrections in kata_tujuan)
[58/82] Processed: 41_Billex.csv (7873 rows, 4018 corrections in kata_asal)
[59/82] Processed: 77_Billex.csv (3735 rows, 315 corrections in kata_tujuan)
[60/82] Processed: 42_Billex.csv (5033 rows, 1932 corrections in kata_asal)
[61/82] Processed: 67_Billex.csv (1422 rows, 1001 corrections in kata_tujuan)
[62/82] Processed: 68_Billex.csv (7083 rows, 643 corrections in kata_tujuan)
[63/82] Processed: 79_Billex.csv (997 rows, 141 corrections in kata_tujuan)
[64/82] Processed: 78_Billex.csv (3191 rows, 255 corrections in kata_tujuan)
[65/82] Processed: 84_Billex.csv (1670 rows, 337 corrections in kata_tujuan)
[66/82] Processed: 74_Billex.csv (2035 rows, 1374 corrections in kata_asal)
[67/82] Processed: 63_Billex.csv (3059 rows, 1375 corrections in kata_asal)
[68/82] Processed: 85_Billex.csv (4604 rows, 224 corrections in kata_tujuan)
[69/82] Processed: 80_Billex.csv (6031 rows, 1362 corrections in kata_tujuan)
[70/82] Processed: 89_Billex.csv (1128 rows, 34 corrections in kata_tujuan)
[71/82] Processed: 8_Billex.csv (202 rows, 115 corrections in kata_asal)
[72/82] Processed: 83_Billex.csv (2342 rows, 1328 corrections in kata_asal)
[73/82] Processed: 90_Billex.csv (3327 rows, 247 corrections in kata_tujuan)
[74/82] Processed: 5_Billex.csv (3032 rows, 1644 corrections in kata_asal)
[75/82] Processed: 94_Billex.csv (633 rows, 130 corrections in kata_tujuan)
[76/82] Processed: 9_Billex.csv (2541 rows, 342 corrections in kata_tujuan)
[77/82] Processed: 82_Billex.csv (2379 rows, 1298 corrections in kata_asal)
[78/82] Processed: 91_Billex.csv (10187 rows, 1126 corrections in kata_tujuan)
[79/82] Processed: 86_Billex.csv (15879 rows, 7110 corrections in kata_tujuan)
[80/82] Processed: 88_Billex.csv (10170 rows, 6667 corrections in kata_asal)
[81/82] Processed: 87_Billex.csv (7686 rows, 3262 corrections in kata_asal)
[82/82] Processed: 81_Billex.csv (35039 rows, 20436 corrections in kata_asal)

## 6. Morphology processor

For each `<id>_Morphology.csv`:

- **dir=1 (Indonesian to Regional)**: both `kata` (headword) and `form` (derived
  form) are Indonesian, spellcheck both.
- **dir=0 (Regional to Indonesian)**: `kata` and `form` are in the regional
  language — passthrough, do not corrupt with the Indonesian lexicon.

The `tag` column is never touched (it's a POS tag, not natural-language
content). The audit file follows the same convention as Billex: original
copies are preserved and a `_corrected` flag is added per column.

In [33]:
def process_morph(file_name: str) -> str:
    try:
        input_file  = MORPH_SRC / file_name
        output_file = MORPH_DST / file_name
        audit_file  = MORPH_DST / file_name.replace('.csv', '_audit.csv')

        if file_name.endswith('_audit.csv'):
            return f'Skip: {file_name} (audit file from upstream)'

        success, is_from_indonesia = get_is_from_indonesia(input_file)
        if not success:
            return f'Skip: No matching ID for {file_name}'

        df = pd.read_csv(input_file)
        if 'kata' not in df.columns or 'form' not in df.columns:
            return f'Skip: {file_name} missing kata/form columns'

        # roles_for_morphology returns ('ind', 'reg') if dir==1 else ('reg', 'ind')
        # Here we only care WHETHER kata/form are Indonesian — they are iff dir==1.
        indonesian_columns = ['kata', 'form'] if is_from_indonesia == 1 else []

        out_df    = df.copy()
        audit_df  = df.copy()
        audit_df['direction'] = is_from_indonesia

        if not indonesian_columns:
            # Regional→Indonesian dict: passthrough.
            out_df.to_csv(output_file, index=False)
            audit_df['kata_corrected'] = False
            audit_df['form_corrected'] = False
            audit_df.to_csv(audit_file, index=False)
            return f'Passthrough (dir=0): {file_name} ({len(out_df)} rows)'

        n_changed_total = 0
        for col in indonesian_columns:
            original = df[col].astype(str).where(df[col].notna(), '')
            corrected = original.apply(fix_cell)
            out_df[col] = corrected
            audit_df[f'{col}_original']  = original
            audit_df[col]                = corrected
            audit_df[f'{col}_corrected'] = original != corrected
            n_changed_total += int((original != corrected).sum())

        out_df.to_csv(output_file, index=False)
        audit_df.to_csv(audit_file, index=False)
        return f'Processed: {file_name} ({len(out_df)} rows, {n_changed_total} corrections in {indonesian_columns})'

    except Exception as e:
        return f'Error in {file_name}: {e}'


morph_files = [
    f for f in os.listdir(MORPH_SRC)
    if f.endswith('.csv') and not f.endswith('_audit.csv')
    and not f.startswith('_')
]
print(f'Found {len(morph_files)} Morphology files to process')

morph_results = []
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
    futures = [executor.submit(process_morph, f) for f in morph_files]
    for count, future in enumerate(concurrent.futures.as_completed(futures), 1):
        msg = future.result()
        morph_results.append(msg)
        print(f'[{count}/{len(morph_files)}] {msg}')

Found 165 Morphology files to process
[1/165] Skip: 0_DerivedBillex.csv missing kata/form columns
[2/165] Skip: 12_DerivedBillex.csv missing kata/form columns
[3/165] Skip: 10_DerivedBillex.csv missing kata/form columns
[4/165] Skip: 11_DerivedBillex.csv missing kata/form columns
[5/165] Skip: 14_DerivedBillex.csv missing kata/form columns
[6/165] Skip: 13_DerivedBillex.csv missing kata/form columns
[7/165] Passthrough (dir=0): 11_Morphology.csv (1805 rows)
[8/165] Skip: 16_DerivedBillex.csv missing kata/form columns
[9/165] Skip: 15_DerivedBillex.csv missing kata/form columns
[10/165] Skip: 17_DerivedBillex.csv missing kata/form columns
[11/165] Passthrough (dir=0): 17_Morphology.csv (237 rows)
[12/165] Skip: 18_DerivedBillex.csv missing kata/form columns
[13/165] Passthrough (dir=0): 18_Morphology.csv (3098 rows)
[14/165] Skip: 19_DerivedBillex.csv missing kata/form columns
[15/165] Processed: 0_Morphology.csv (16 rows, 18 corrections in ['kata', 'form'])
[16/165] Skip: 1_DerivedBillex.csv missing kata/form columns
[17/165] Passthrough (dir=0): 1_Morphology.csv (686 rows)
[18/165] Skip: 20_DerivedBillex.csv missing kata/form columns
[19/165] Passthrough (dir=0): 20_Morphology.csv (326 rows)
[20/165] Skip: 21_DerivedBillex.csv missing kata/form columns
[21/165] Processed: 13_Morphology.csv (97 rows, 100 corrections in ['kata', 'form'])
[22/165] Skip: 22_DerivedBillex.csv missing kata/form columns
[23/165] Passthrough (dir=0): 22_Morphology.csv (795 rows)
[24/165] Skip: 23_DerivedBillex.csv missing kata/form columns
[25/165] Passthrough (dir=0): 23_Morphology.csv (684 rows)
[26/165] Skip: 24_DerivedBillex.csv missing kata/form columns
[27/165] Passthrough (dir=0): 24_Morphology.csv (2707 rows)
[28/165] Skip: 25_DerivedBillex.csv missing kata/form columns
[29/165] Processed: 16_Morphology.csv (1208 rows, 802 corrections in ['kata', 'form'])
[30/165] Skip: 26_DerivedBillex.csv missing kata/form columns
[31/165] Processed: 10_Morphology.csv (1472 rows, 816 corrections in ['kata', 'form'])
[32/165] Skip: 27_DerivedBillex.csv missing kata/form columns
[33/165] Processed: 21_Morphology.csv (741 rows, 474 corrections in ['kata', 'form'])
[34/165] Skip: 28_DerivedBillex.csv missing kata/form columns
[35/165] Passthrough (dir=0): 28_Morphology.csv (2186 rows)
[36/165] Skip: 29_DerivedBillex.csv missing kata/form columns
[37/165] Passthrough (dir=0): 29_Morphology.csv (315 rows)
[38/165] Skip: 2_DerivedBillex.csv missing kata/form columns
[39/165] Passthrough (dir=0): 2_Morphology.csv (726 rows)
[40/165] Skip: 31_DerivedBillex.csv missing kata/form columns
[41/165] Passthrough (dir=0): 31_Morphology.csv (65 rows)
[42/165] Skip: 32_DerivedBillex.csv missing kata/form columns
[43/165] Passthrough (dir=0): 32_Morphology.csv (101 rows)
[44/165] Skip: 33_DerivedBillex.csv missing kata/form columns
[45/165] Passthrough (dir=0): 33_Morphology.csv (434 rows)
[46/165] Skip: 34_DerivedBillex.csv missing kata/form columns
[47/165] Processed: 25_Morphology.csv (1163 rows, 654 corrections in ['kata', 'form'])
[48/165] Skip: 35_DerivedBillex.csv missing kata/form columns
[49/165] Processed: 27_Morphology.csv (1285 rows, 880 corrections in ['kata', 'form'])
[50/165] Skip: 36_DerivedBillex.csv missing kata/form columns
[51/165] Processed: 14_Morphology.csv (1860 rows, 1323 corrections in ['kata', 'form'])
[52/165] Skip: 37_DerivedBillex.csv missing kata/form columns
[53/165] Processed: 26_Morphology.csv (1731 rows, 1399 corrections in ['kata', 'form'])
[54/165] Skip: 38_DerivedBillex.csv missing kata/form columns
[55/165] Processed: 36_Morphology.csv (1403 rows, 840 corrections in ['kata', 'form'])
[56/165] Skip: 39_DerivedBillex.csv missing kata/form columns
[57/165] Passthrough (dir=0): 39_Morphology.csv (382 rows)
[58/165] Skip: 3_DerivedBillex.csv missing kata/form columns
[59/165] Passthrough (dir=0): 3_Morphology.csv (651 rows)
[60/165] Skip: 41_DerivedBillex.csv missing kata/form columns
[61/165] Processed: 35_Morphology.csv (1295 rows, 808 corrections in ['kata', 'form'])
[62/165] Skip: 42_DerivedBillex.csv missing kata/form columns
[63/165] Processed: 19_Morphology.csv (3163 rows, 1832 corrections in ['kata', 'form'])
[64/165] Skip: 43_DerivedBillex.csv missing kata/form columns
[65/165] Processed: 15_Morphology.csv (1342 rows, 1189 corrections in ['kata', 'form'])
[66/165] Skip: 44_DerivedBillex.csv missing kata/form columns
[67/165] Passthrough (dir=0): 44_Morphology.csv (275 rows)
[68/165] Skip: 45_DerivedBillex.csv missing kata/form columns
[69/165] Processed: 37_Morphology.csv (1236 rows, 905 corrections in ['kata', 'form'])
[70/165] Skip: 46_DerivedBillex.csv missing kata/form columns
[71/165] Passthrough (dir=0): 46_Morphology.csv (5428 rows)
[72/165] Skip: No matching ID for 47_DerivedBillex.csv
[73/165] Skip: No matching ID for 47_Morphology.csv
[74/165] Skip: 48_DerivedBillex.csv missing kata/form columns
[75/165] Passthrough (dir=0): 48_Morphology.csv (270 rows)
[76/165] Skip: 4_DerivedBillex.csv missing kata/form columns
[77/165] Processed: 12_Morphology.csv (2729 rows, 2910 corrections in ['kata', 'form'])
[78/165] Skip: 50_DerivedBillex.csv missing kata/form columns
[79/165] Processed: 50_Morphology.csv (37 rows, 59 corrections in ['kata', 'form'])
[80/165] Skip: 51_DerivedBillex.csv missing kata/form columns
[81/165] Passthrough (dir=0): 51_Morphology.csv (196 rows)
[82/165] Skip: 52_DerivedBillex.csv missing kata/form columns
[83/165] Passthrough (dir=0): 52_Morphology.csv (402 rows)
[84/165] Passthrough (dir=0): 53_Morphology.csv (0 rows)
[85/165] Skip: 54_DerivedBillex.csv missing kata/form columns
[86/165] Processed: 38_Morphology.csv (1205 rows, 1262 corrections in ['kata', 'form'])
[87/165] Skip: 55_DerivedBillex.csv missing kata/form columns
[88/165] Processed: 4_Morphology.csv (1181 rows, 482 corrections in ['kata', 'form'])
[89/165] Skip: 56_DerivedBillex.csv missing kata/form columns
[90/165] Processed: 43_Morphology.csv (1580 rows, 762 corrections in ['kata', 'form'])
[91/165] Skip: 57_DerivedBillex.csv missing kata/form columns
[92/165] Passthrough (dir=0): 56_Morphology.csv (189 rows)
[93/165] Skip: 58_DerivedBillex.csv missing kata/form columns
[94/165] Passthrough (dir=0): 57_Morphology.csv (1447 rows)
[95/165] Passthrough (dir=0): 58_Morphology.csv (274 rows)
[96/165] Skip: 5_DerivedBillex.csv missing kata/form columns
[97/165] Skip: 60_DerivedBillex.csv missing kata/form columns
[98/165] Passthrough (dir=0): 60_Morphology.csv (268 rows)
[99/165] Skip: 61_DerivedBillex.csv missing kata/form columns
[100/165] Passthrough (dir=0): 61_Morphology.csv (290 rows)
[101/165] Skip: 62_DerivedBillex.csv missing kata/form columns
[102/165] Passthrough (dir=0): 62_Morphology.csv (298 rows)
[103/165] Processed: 45_Morphology.csv (1178 rows, 749 corrections in ['kata', 'form'])
[104/165] Skip: 63_DerivedBillex.csv missing kata/form columns
[105/165] Skip: 64_DerivedBillex.csv missing kata/form columns
[106/165] Passthrough (dir=0): 64_Morphology.csv (662 rows)
[107/165] Skip: 65_DerivedBillex.csv missing kata/form columns
[108/165] Passthrough (dir=0): 65_Morphology.csv (1746 rows)
[109/165] Skip: 66_DerivedBillex.csv missing kata/form columns
[110/165] Passthrough (dir=0): 66_Morphology.csv (329 rows)
[111/165] Skip: 67_DerivedBillex.csv missing kata/form columns
[112/165] Passthrough (dir=0): 67_Morphology.csv (1072 rows)
[113/165] Skip: 68_DerivedBillex.csv missing kata/form columns
[114/165] Passthrough (dir=0): 68_Morphology.csv (2445 rows)
[115/165] Skip: 69_DerivedBillex.csv missing kata/form columns
[116/165] Passthrough (dir=0): 69_Morphology.csv (347 rows)
[117/165] Skip: 71_DerivedBillex.csv missing kata/form columns
[118/165] Passthrough (dir=0): 71_Morphology.csv (14 rows)
[119/165] Skip: 74_DerivedBillex.csv missing kata/form columns
[120/165] Processed: 74_Morphology.csv (79 rows, 117 corrections in ['kata', 'form'])
[121/165] Skip: 77_DerivedBillex.csv missing kata/form columns
[122/165] Passthrough (dir=0): 77_Morphology.csv (864 rows)
[123/165] Skip: 78_DerivedBillex.csv missing kata/form columns
[124/165] Passthrough (dir=0): 78_Morphology.csv (1359 rows)
[125/165] Skip: 79_DerivedBillex.csv missing kata/form columns
[126/165] Passthrough (dir=0): 79_Morphology.csv (742 rows)
[127/165] Skip: 80_DerivedBillex.csv missing kata/form columns
[128/165] Passthrough (dir=0): 80_Morphology.csv (2802 rows)
[129/165] Skip: 81_DerivedBillex.csv missing kata/form columns
[130/165] Processed: 55_Morphology.csv (871 rows, 595 corrections in ['kata', 'form'])
[131/165] Skip: 82_DerivedBillex.csv missing kata/form columns
[132/165] Processed: 34_Morphology.csv (1990 rows, 2604 corrections in ['kata', 'form'])
[133/165] Skip: 83_DerivedBillex.csv missing kata/form columns
[134/165] Processed: 42_Morphology.csv (2247 rows, 1586 corrections in ['kata', 'form'])
[135/165] Skip: 84_DerivedBillex.csv missing kata/form columns
[136/165] Passthrough (dir=0): 84_Morphology.csv (578 rows)
[137/165] Skip: 85_DerivedBillex.csv missing kata/form columns
[138/165] Passthrough (dir=0): 85_Morphology.csv (2155 rows)
[139/165] Skip: 86_DerivedBillex.csv missing kata/form columns
[140/165] Passthrough (dir=0): 86_Morphology.csv (7741 rows)
[141/165] Skip: 87_DerivedBillex.csv missing kata/form columns
[142/165] Processed: 63_Morphology.csv (390 rows, 313 corrections in ['kata', 'form'])
[143/165] Skip: 88_DerivedBillex.csv missing kata/form columns
[144/165] Processed: 83_Morphology.csv (1024 rows, 917 corrections in ['kata', 'form'])
[145/165] Skip: 89_DerivedBillex.csv missing kata/form columns
[146/165] Passthrough (dir=0): 89_Morphology.csv (102 rows)
[147/165] Skip: 8_DerivedBillex.csv missing kata/form columns
[148/165] Processed: 8_Morphology.csv (88 rows, 129 corrections in ['kata', 'form'])
[149/165] Skip: 90_DerivedBillex.csv missing kata/form columns
[150/165] Passthrough (dir=0): 90_Morphology.csv (1060 rows)
[151/165] Skip: 91_DerivedBillex.csv missing kata/form columns
[152/165] Passthrough (dir=0): 91_Morphology.csv (3545 rows)
[153/165] Processed: 5_Morphology.csv (1386 rows, 974 corrections in ['kata', 'form'])
[154/165] Skip: 94_DerivedBillex.csv missing kata/form columns
[155/165] Passthrough (dir=0): 94_Morphology.csv (262 rows)
[156/165] Skip: 9_DerivedBillex.csv missing kata/form columns
[157/165] Skip: No matching ID for ocr_pos_ambiguous.csv
[158/165] Skip: No matching ID for ocr_pos_fixups.csv
[159/165] Passthrough (dir=0): 9_Morphology.csv (694 rows)
[160/165] Processed: 82_Morphology.csv (861 rows, 1022 corrections in ['kata', 'form'])
[161/165] Processed: 54_Morphology.csv (985 rows, 625 corrections in ['kata', 'form'])
[162/165] Processed: 41_Morphology.csv (2694 rows, 3618 corrections in ['kata', 'form'])
[163/165] Processed: 87_Morphology.csv (2737 rows, 2803 corrections in ['kata', 'form'])
[164/165] Processed: 88_Morphology.csv (5107 rows, 6918 corrections in ['kata', 'form'])
[165/165] Processed: 81_Morphology.csv (21892 rows, 28248 corrections in ['kata', 'form'])

## 7. Per-dictionary correction summaries

Re-reads the audit files to build a wide summary table. Useful for the thesis
appendix to report, per dictionary, how many cells the spellchecker changed in
each resource. Saves as `_billex_summary.csv` and `_morph_summary.csv` next to
the output files.

In [34]:
def billex_summary_row(audit_path: Path) -> Optional[dict]:
    dict_id = parse_dict_id(audit_path.name)
    if dict_id is None:
        return None
    df = pd.read_csv(audit_path)
    if df.empty or 'direction' not in df.columns:
        return {
            'dict_id': dict_id,
            'direction': -1,
            'indonesian_column': '',
            'rows': len(df),
            'corrected_cells': 0,
        }
    direction = int(df['direction'].iloc[0])
    ind_col = 'kata_asal' if direction == 1 else 'kata_tujuan'
    flag = f'{ind_col}_corrected'
    return {
        'dict_id': dict_id,
        'direction': direction,
        'indonesian_column': ind_col,
        'rows': len(df),
        'corrected_cells': int(df[flag].sum()) if flag in df.columns else 0,
    }


def morph_summary_row(audit_path: Path) -> Optional[dict]:
    dict_id = parse_dict_id(audit_path.name)
    if dict_id is None:
        return None
    df = pd.read_csv(audit_path)
    if df.empty or 'direction' not in df.columns:
        return {
            'dict_id': dict_id,
            'direction': -1,
            'rows': len(df),
            'kata_corrected_cells': 0,
            'form_corrected_cells': 0,
            'total_corrected_cells': 0,
        }
    direction = int(df['direction'].iloc[0])
    kata_changed = int(df['kata_corrected'].sum()) if 'kata_corrected' in df.columns else 0
    form_changed = int(df['form_corrected'].sum()) if 'form_corrected' in df.columns else 0
    return {
        'dict_id': dict_id,
        'direction': direction,
        'rows': len(df),
        'kata_corrected_cells': kata_changed,
        'form_corrected_cells': form_changed,
        'total_corrected_cells': kata_changed + form_changed,
    }

## 8. Cross-resource sanity checks

Two consistency checks after the run:

1. Every Billex/Morph file in the source directory should now have a matching
   output file.
2. The number of rows must be **exactly** preserved per file. The
   spellchecker only edits cell values; it must not add or drop rows.

In [35]:
def check_row_parity(src_dir: Path, dst_dir: Path, suffix: str) -> pd.DataFrame:
    records = []
    for src in sorted(src_dir.glob(f'*_{suffix}.csv')):
        if src.name.endswith('_audit.csv'):
            continue
        dst = dst_dir / src.name
        if not dst.exists():
            records.append({'file': src.name, 'src_rows': -1, 'dst_rows': -1, 'status': 'MISSING'})
            continue
        try:
            n_src = len(pd.read_csv(src))
            n_dst = len(pd.read_csv(dst))
        except Exception as e:
            records.append({'file': src.name, 'src_rows': -1, 'dst_rows': -1, 'status': f'ERR: {e}'})
            continue
        status = 'OK' if n_src == n_dst else 'MISMATCH'
        records.append({'file': src.name, 'src_rows': n_src, 'dst_rows': n_dst, 'status': status})
    return pd.DataFrame(records)


billex_parity = check_row_parity(BILLEX_SRC, BILLEX_DST, 'Billex')
morph_parity  = check_row_parity(MORPH_SRC,  MORPH_DST,  'Morphology')

print('Billex parity:')
print(f"  OK:       {(billex_parity['status'] == 'OK').sum()}")
print(f"  MISSING:  {(billex_parity['status'] == 'MISSING').sum()}")
print(f"  MISMATCH: {(billex_parity['status'] == 'MISMATCH').sum()}")
bad = billex_parity[billex_parity['status'] != 'OK']
if not bad.empty:
    display(bad)

print('\nMorphology parity:')
print(f"  OK:       {(morph_parity['status'] == 'OK').sum()}")
print(f"  MISSING:  {(morph_parity['status'] == 'MISSING').sum()}")
print(f"  MISMATCH: {(morph_parity['status'] == 'MISMATCH').sum()}")
bad = morph_parity[morph_parity['status'] != 'OK']
if not bad.empty:
    display(bad)

Billex parity:
  OK:       81
  MISSING:  1
  MISMATCH: 0

             file  src_rows  dst_rows   status
39  47_Billex.csv        -1        -1  MISSING

Morphology parity:
  OK:       81
  MISSING:  1
  MISMATCH: 0

                 file  src_rows  dst_rows   status
39  47_Morphology.csv        -1        -1  MISSING

## 9. Spot-check a few corrections

Prints sample original to corrected pairs from one Indonesian-source Billex
(`dict 4`, Jambi) and one Indonesian-source Morphology (`dict 18`, Javanese).
Sanity check that the corrections look reasonable before downstream stages
consume the output.

In [36]:
def spot_check_billex(dict_id: str, n: int = 15) -> None:
    audit = BILLEX_DST / f'{dict_id}_Billex_audit.csv'
    if not audit.exists():
        print(f'  (no audit file for dict {dict_id})')
        return
    df = pd.read_csv(audit)
    direction = int(df['direction'].iloc[0]) if 'direction' in df.columns else 1
    ind_col = 'kata_asal' if direction == 1 else 'kata_tujuan'
    flag = f'{ind_col}_corrected'
    orig = f'{ind_col}_original'
    if flag not in df.columns:
        print(f'  (no correction flag in dict {dict_id})')
        return
    changed = df[df[flag]][[orig, ind_col]].drop_duplicates().head(n)
    print(f'  Dict {dict_id} Billex ({ind_col}, dir={direction}): {df[flag].sum()} cells changed')
    print(changed.to_string(index=False))


def spot_check_morph(dict_id: str, n: int = 15) -> None:
    audit = MORPH_DST / f'{dict_id}_Morphology_audit.csv'
    if not audit.exists():
        print(f'  (no audit file for dict {dict_id})')
        return
    df = pd.read_csv(audit)
    direction = int(df['direction'].iloc[0]) if 'direction' in df.columns else 1
    if direction != 1:
        print(f'  Dict {dict_id} Morphology: dir={direction}, passthrough (no Indonesian columns)')
        return
    changed_rows = df[df.get('kata_corrected', False) | df.get('form_corrected', False)]
    cols = ['kata_original', 'kata', 'form_original', 'form']
    cols = [c for c in cols if c in df.columns]
    print(f'  Dict {dict_id} Morphology (dir=1): '
          f"kata={df.get('kata_corrected', pd.Series(dtype=bool)).sum()} "
          f"form={df.get('form_corrected', pd.Series(dtype=bool)).sum()} corrections")
    print(changed_rows[cols].drop_duplicates().head(n).to_string(index=False))


print('=== Billex sample (dict 4) ===')
spot_check_billex('4')
print('\n=== Morphology sample (dict 18) ===')
spot_check_morph('18')

=== Billex sample (dict 4) ===
  Dict 4 Billex (kata_asal, dir=1): 1425 cells changed
kata_asal_original   kata_asal
       mengabdikan mengabaikan
         melalekan   melakukan
        manyimpang  menyimpang
             kiabu        kabu
          sukonian    sokongan
            acagha       acara
        pengacagha   pengacara
          ndulikan   pedulikan
        mengadokan  mengadakan
            adodak      adonan
          beghadap    berhadap
           ngadili   mengadili
           campugh      campur
         campughan    campuran
          ngadukan    ngajukan

=== Morphology sample (dict 18) ===
  Dict 18 Morphology: dir=0, passthrough (no Indonesian columns)

## 10. Notes

- **Why a separate `13.` / `14.` directory?** Mirrors the convention used for
  Parcor (`12. Parallel Corpus - Spelling Checker`) so each resource keeps
  pre- and post-spellchecker copies side by side. Downstream notebooks can
  switch between the two by changing one path.

- **Switching dictionary strategy.** The same JSON dictionary toggle works
  here — flip `DICT_PATH` to `indonesian_dict_strategy_B.json` or
  `indonesian_dict_strategy_C.json` and rerun. Recommended to record which
  strategy was used by saving the active path into `_billex_summary.csv` /
  `_morph_summary.csv` as a column for the thesis appendix (left as a TODO).

- **What this notebook deliberately does NOT do.**
  - It does not re-run any of the upstream batch fixes (`Fix Billex Headword
    Batch`, `Fix Morphology Batch`). Those must run first to produce the
    `*_Fixed` directories this notebook reads from.
  - It does not touch Parcor.
  - It does not spellcheck regional-language content under any circumstances,
    even when the Indonesian dictionary contains plausible-looking matches.